<a href="https://colab.research.google.com/github/kollamohanchaitanya/Data-Science-projects/blob/main/AdaBoost_Ensemble_with_Decision_Trees_as_the_base_learner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade tensorflow

In [ ]:
from __future__ import print_function
import pandas as pd
pd.__version__

'1.3.5'

In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
#Mouting the drive to load a simple dataset stored on the google drive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
spam_dataset_dataframe = pd.read_csv("/content/gdrive/My Drive/spam.csv", sep = ',')

In [ ]:
import numpy as np

In [ ]:
def split_train_test(data,test_ratio):
  np.random.seed(42) # fix the seed if you want to generate the same
  shuffled_indices = np.random.permutation(len(data))
  test_set_size = int(len(data)*test_ratio)
  test_indices = shuffled_indices[:test_set_size]
  train_indices = shuffled_indices[test_set_size:]
  return data.iloc[train_indices], data.iloc[test_indices]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
spam_training_set, spam_test_set = train_test_split(spam_dataset_dataframe, test_size=0.25,random_state=1000)
spam_dataset_dataframe.keys()


In [ ]:
spam_training_data, spam_training_target = spam_training_set[["make", "address", "all", "3d", "our", "over", "remove", 
    "internet", "order", "mail", "receive", "will", "people", "report", "addresses", 
    "free", "business", "email", "you", "credit", "your", "font", "0", "money", 
    "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", 
    "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", 
    "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", 
    "pound", "cap_avg", "cap_long", "cap_total"]], spam_training_set['Class']
spam_test_data, spam_test_target = spam_test_set[["make", "address", "all", "3d", "our", "over", "remove", 
    "internet", "order", "mail", "receive", "will", "people", "report", "addresses", 
    "free", "business", "email", "you", "credit", "your", "font", "0", "money", 
    "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", 
    "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", 
    "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", 
    "pound", "cap_avg", "cap_long", "cap_total"]], spam_test_set['Class']

In [ ]:
# FUSED MODEL

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#clf = RandomForestClassifier(n_estimators=100)
#clf = DecisionTreeClassifier(criterion = "entropy")
clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeighborsClassifier(n_neighbors=7)
#clf = AdaBoostClassifier(n_estimators = 200)
#LRI = LogisticRegression()
clf_lr = LogisticRegression()
clf_gnb = GaussianNB()
#clf = AdaBoostClassifier(n_estimators = 200,base_estimator=LRI)
eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')
#clf.fit(spam_training_data,spam_training_target)
eclf.fit(spam_training_data,spam_training_target)

In [ ]:
#spam_test_target_predict=clf.predict(spam_test_data)
spam_test_target_predict =eclf.predict(spam_test_data)
confusion_matrix(spam_test_target,spam_test_target_predict)
#classification_report(spam_test_target,spam_test_target_predict)

array([[638,  61],
       [ 24, 428]])

In [ ]:
accuracy_score(spam_test_target,spam_test_target_predict)

0.9261511728931364

In [ ]:
#Adaboost classifier using decisiontree as base_learner

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#clf = RandomForestClassifier(n_estimators=100)
clf = DecisionTreeClassifier(criterion = "entropy")
#clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeighborsClassifier(n_neighbors=7)
#clf = AdaBoostClassifier(n_estimators = 200)
#LRI = LogisticRegression()
#clf_lr = LogisticRegression()
#clf_gnb = GaussianNB()
clf = AdaBoostClassifier(n_estimators = 200,base_estimator=clf)
#eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')
clf.fit(spam_training_data,spam_training_target)
#eclf.fit(spam_training_data,spam_training_target)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy'),
                   n_estimators=200)

In [ ]:
#spam_test_target_predict=clf.predict(spam_test_data)
spam_test_target_predict =eclf.predict(spam_test_data)
confusion_matrix(spam_test_target,spam_test_target_predict)
#classification_report(spam_test_target,spam_test_target_predict)

array([[638,  61],
       [ 24, 428]])

In [ ]:
accuracy_score(spam_test_target,spam_test_target_predict)

0.9261511728931364

In [ ]:
#Adaboost classifier using Random forest as base_learner

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
clf = RandomForestClassifier()
#clf = DecisionTreeClassifier(criterion = "entropy")
#clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeighborsClassifier(n_neighbors=7)
#clf = AdaBoostClassifier(n_estimators = 200)
#LRI = LogisticRegression()
#clf_lr = LogisticRegression()
#clf_gnb = GaussianNB()
clf = AdaBoostClassifier(n_estimators = 200,base_estimator=clf)
#eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')
clf.fit(spam_training_data,spam_training_target)
#eclf.fit(spam_training_data,spam_training_target)

AdaBoostClassifier(base_estimator=RandomForestClassifier(), n_estimators=200)

In [ ]:
#spam_test_target_predict=clf.predict(spam_test_data)
spam_test_target_predict =eclf.predict(spam_test_data)
confusion_matrix(spam_test_target,spam_test_target_predict)
#classification_report(spam_test_target,spam_test_target_predict)

array([[638,  61],
       [ 24, 428]])

In [ ]:
accuracy_score(spam_test_target,spam_test_target_predict)

0.9261511728931364

In [ ]:
#50%-50%

spam_training_set, spam_test_set = train_test_split(spam_dataset_dataframe, test_size=0.5,random_state=1000)
spam_dataset_dataframe.keys()

In [ ]:
spam_training_data, spam_training_target = spam_training_set[["make", "address", "all", "3d", "our", "over", "remove", 
    "internet", "order", "mail", "receive", "will", "people", "report", "addresses", 
    "free", "business", "email", "you", "credit", "your", "font", "0", "money", 
    "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", 
    "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", 
    "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", 
    "pound", "cap_avg", "cap_long", "cap_total"]], spam_training_set['Class']
spam_test_data, spam_test_target = spam_test_set[["make", "address", "all", "3d", "our", "over", "remove", 
    "internet", "order", "mail", "receive", "will", "people", "report", "addresses", 
    "free", "business", "email", "you", "credit", "your", "font", "0", "money", 
    "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", 
    "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", 
    "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", 
    "pound", "cap_avg", "cap_long", "cap_total"]], spam_test_set['Class']

In [ ]:
# FUSED MODEL for #50%-50%

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#clf = RandomForestClassifier(n_estimators=100)
#clf = DecisionTreeClassifier(criterion = "entropy")
clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeighborsClassifier(n_neighbors=7)
#clf = AdaBoostClassifier(n_estimators = 200)
#LRI = LogisticRegression()
clf_lr = LogisticRegression()
clf_gnb = GaussianNB()
#clf = AdaBoostClassifier(n_estimators = 200,base_estimator=LRI)
eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')
#clf.fit(spam_training_data,spam_training_target)
eclf.fit(spam_training_data,spam_training_target)

In [ ]:
#spam_test_target_predict=clf.predict(spam_test_data)
spam_test_target_predict =eclf.predict(spam_test_data)
confusion_matrix(spam_test_target,spam_test_target_predict)
#classification_report(spam_test_target,spam_test_target_predict)

array([[1286,  105],
       [  56,  854]])

In [ ]:
accuracy_score(spam_test_target,spam_test_target_predict)

0.9300304215558453

In [ ]:
#Adaboost classifier using decisiontree as base_learner for #50%-50%

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#clf = RandomForestClassifier(n_estimators=100)
clf = DecisionTreeClassifier(criterion = "entropy")
#clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeighborsClassifier(n_neighbors=7)
#clf = AdaBoostClassifier(n_estimators = 200)
#LRI = LogisticRegression()
#clf_lr = LogisticRegression()
#clf_gnb = GaussianNB()
clf = AdaBoostClassifier(n_estimators = 200,base_estimator=clf)
#eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')
clf.fit(spam_training_data,spam_training_target)
#eclf.fit(spam_training_data,spam_training_target)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy'),
                   n_estimators=200)

In [ ]:
#spam_test_target_predict=clf.predict(spam_test_data)
spam_test_target_predict =eclf.predict(spam_test_data)
confusion_matrix(spam_test_target,spam_test_target_predict)
#classification_report(spam_test_target,spam_test_target_predict)

array([[1286,  105],
       [  56,  854]])

In [ ]:
accuracy_score(spam_test_target,spam_test_target_predict)

0.9300304215558453

In [ ]:
#60%-40%
spam_training_set, spam_test_set = train_test_split(spam_dataset_dataframe, test_size=0.4,random_state=1000)
spam_dataset_dataframe.keys()



Index(['make', 'address', 'all', '3d', 'our', 'over', 'remove', 'internet',
       'order', 'mail', 'receive', 'will', 'people', 'report', 'addresses',
       'free', 'business', 'email', 'you', 'credit', 'your', 'font', '0',
       'money', 'hp', 'hpl', 'george', '650', 'lab', 'labs', 'telnet', '857',
       'data', '415', '85', 'technology', '1999', 'parts', 'pm', 'direct',
       'cs', 'meeting', 'original', 'project', 're', 'edu', 'table',
       'conference', 'semicol', 'paren', 'bracket', 'bang', 'dollar', 'pound',
       'cap_avg', 'cap_long', 'cap_total', 'Class'],
      dtype='object')

In [ ]:
spam_training_data, spam_training_target = spam_training_set[["make", "address", "all", "3d", "our", "over", "remove", 
    "internet", "order", "mail", "receive", "will", "people", "report", "addresses", 
    "free", "business", "email", "you", "credit", "your", "font", "0", "money", 
    "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", 
    "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", 
    "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", 
    "pound", "cap_avg", "cap_long", "cap_total"]], spam_training_set['Class']
spam_test_data, spam_test_target = spam_test_set[["make", "address", "all", "3d", "our", "over", "remove", 
    "internet", "order", "mail", "receive", "will", "people", "report", "addresses", 
    "free", "business", "email", "you", "credit", "your", "font", "0", "money", 
    "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", 
    "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", 
    "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", 
    "pound", "cap_avg", "cap_long", "cap_total"]], spam_test_set['Class']

In [ ]:
# FUSED MODEL for #60%-40%

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#clf = RandomForestClassifier(n_estimators=100)
#clf = DecisionTreeClassifier(criterion = "entropy")
clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeighborsClassifier(n_neighbors=7)
#clf = AdaBoostClassifier(n_estimators = 200)
#LRI = LogisticRegression()
clf_lr = LogisticRegression()
clf_gnb = GaussianNB()
#clf = AdaBoostClassifier(n_estimators = 200,base_estimator=LRI)
eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')
#clf.fit(spam_training_data,spam_training_target)
eclf.fit(spam_training_data,spam_training_target)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


VotingClassifier(estimators=[('DT',
                              DecisionTreeClassifier(criterion='entropy')),
                             ('LR', LogisticRegression()),
                             ('GNB', GaussianNB())])

In [ ]:

#spam_test_target_predict=clf.predict(spam_test_data)
spam_test_target_predict =eclf.predict(spam_test_data)
confusion_matrix(spam_test_target,spam_test_target_predict)
#classification_report(spam_test_target,spam_test_target_predict

array([[1029,   89],
       [  41,  682]])

In [ ]:
accuracy_score(spam_test_target,spam_test_target_predict)

0.9293862031504617

In [ ]:
#Adaboost classifier using decisiontree as base_learner for #60%-40%

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#clf = RandomForestClassifier(n_estimators=100)
clf = DecisionTreeClassifier(criterion = "entropy")
#clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeighborsClassifier(n_neighbors=7)
#clf = AdaBoostClassifier(n_estimators = 200)
#LRI = LogisticRegression()
#clf_lr = LogisticRegression()
#clf_gnb = GaussianNB()
clf = AdaBoostClassifier(n_estimators = 200,base_estimator=clf)
#eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')
clf.fit(spam_training_data,spam_training_target)
#eclf.fit(spam_training_data,spam_training_target)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy'),
                   n_estimators=200)

In [ ]:
#spam_test_target_predict=clf.predict(spam_test_data)
spam_test_target_predict =eclf.predict(spam_test_data)
confusion_matrix(spam_test_target,spam_test_target_predict)
#classification_report(spam_test_target,spam_test_target_predict)

array([[1029,   89],
       [  41,  682]])

In [ ]:
accuracy_score(spam_test_target,spam_test_target_predict)

0.9293862031504617

In [ ]:
#70%-30%
spam_training_set, spam_test_set = train_test_split(spam_dataset_dataframe, test_size=0.3,random_state=1000)
spam_dataset_dataframe.keys()

Index(['make', 'address', 'all', '3d', 'our', 'over', 'remove', 'internet',
       'order', 'mail', 'receive', 'will', 'people', 'report', 'addresses',
       'free', 'business', 'email', 'you', 'credit', 'your', 'font', '0',
       'money', 'hp', 'hpl', 'george', '650', 'lab', 'labs', 'telnet', '857',
       'data', '415', '85', 'technology', '1999', 'parts', 'pm', 'direct',
       'cs', 'meeting', 'original', 'project', 're', 'edu', 'table',
       'conference', 'semicol', 'paren', 'bracket', 'bang', 'dollar', 'pound',
       'cap_avg', 'cap_long', 'cap_total', 'Class'],
      dtype='object')

In [ ]:
spam_training_data, spam_training_target = spam_training_set[["make", "address", "all", "3d", "our", "over", "remove", 
    "internet", "order", "mail", "receive", "will", "people", "report", "addresses", 
    "free", "business", "email", "you", "credit", "your", "font", "0", "money", 
    "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", 
    "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", 
    "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", 
    "pound", "cap_avg", "cap_long", "cap_total"]], spam_training_set['Class']
spam_test_data, spam_test_target = spam_test_set[["make", "address", "all", "3d", "our", "over", "remove", 
    "internet", "order", "mail", "receive", "will", "people", "report", "addresses", 
    "free", "business", "email", "you", "credit", "your", "font", "0", "money", 
    "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", 
    "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", 
    "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", 
    "pound", "cap_avg", "cap_long", "cap_total"]], spam_test_set['Class']

In [ ]:
# FUSED MODEL for 70%-30%

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#clf = RandomForestClassifier(n_estimators=100)
#clf = DecisionTreeClassifier(criterion = "entropy")
clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeighborsClassifier(n_neighbors=7)
#clf = AdaBoostClassifier(n_estimators = 200)
#LRI = LogisticRegression()
clf_lr = LogisticRegression()
clf_gnb = GaussianNB()
#clf = AdaBoostClassifier(n_estimators = 200,base_estimator=LRI)
eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')
#clf.fit(spam_training_data,spam_training_target)
eclf.fit(spam_training_data,spam_training_target)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


VotingClassifier(estimators=[('DT',
                              DecisionTreeClassifier(criterion='entropy')),
                             ('LR', LogisticRegression()),
                             ('GNB', GaussianNB())])

In [ ]:
#spam_test_target_predict=clf.predict(spam_test_data)
spam_test_target_predict =eclf.predict(spam_test_data)
confusion_matrix(spam_test_target,spam_test_target_predict)
#classification_report(spam_test_target,spam_test_target_predict)


array([[766,  68],
       [ 30, 517]])

In [ ]:
accuracy_score(spam_test_target,spam_test_target_predict)

0.9290369297610427

In [ ]:
#Adaboost classifier using decisiontree as base_learner for 70%-30%

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#clf = RandomForestClassifier(n_estimators=100)
clf = DecisionTreeClassifier(criterion = "entropy")
#clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeighborsClassifier(n_neighbors=7)
#clf = AdaBoostClassifier(n_estimators = 200)
#LRI = LogisticRegression()
#clf_lr = LogisticRegression()
#clf_gnb = GaussianNB()
clf = AdaBoostClassifier(n_estimators = 200,base_estimator=clf)
#eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')
clf.fit(spam_training_data,spam_training_target)
#eclf.fit(spam_training_data,spam_training_target)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy'),
                   n_estimators=200)

In [ ]:
#spam_test_target_predict=clf.predict(spam_test_data)
spam_test_target_predict =eclf.predict(spam_test_data)
confusion_matrix(spam_test_target,spam_test_target_predict)
#classification_report(spam_test_target,spam_test_target_predict)



array([[766,  68],
       [ 30, 517]])

In [ ]:
accuracy_score(spam_test_target,spam_test_target_predict)

0.9290369297610427

In [ ]:
#80%-20%
spam_training_set, spam_test_set = train_test_split(spam_dataset_dataframe, test_size=0.2,random_state=1000)
spam_dataset_dataframe.keys()









Index(['make', 'address', 'all', '3d', 'our', 'over', 'remove', 'internet',
       'order', 'mail', 'receive', 'will', 'people', 'report', 'addresses',
       'free', 'business', 'email', 'you', 'credit', 'your', 'font', '0',
       'money', 'hp', 'hpl', 'george', '650', 'lab', 'labs', 'telnet', '857',
       'data', '415', '85', 'technology', '1999', 'parts', 'pm', 'direct',
       'cs', 'meeting', 'original', 'project', 're', 'edu', 'table',
       'conference', 'semicol', 'paren', 'bracket', 'bang', 'dollar', 'pound',
       'cap_avg', 'cap_long', 'cap_total', 'Class'],
      dtype='object')

In [ ]:
spam_training_data, spam_training_target = spam_training_set[["make", "address", "all", "3d", "our", "over", "remove", 
    "internet", "order", "mail", "receive", "will", "people", "report", "addresses", 
    "free", "business", "email", "you", "credit", "your", "font", "0", "money", 
    "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", 
    "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", 
    "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", 
    "pound", "cap_avg", "cap_long", "cap_total"]], spam_training_set['Class']
spam_test_data, spam_test_target = spam_test_set[["make", "address", "all", "3d", "our", "over", "remove", 
    "internet", "order", "mail", "receive", "will", "people", "report", "addresses", 
    "free", "business", "email", "you", "credit", "your", "font", "0", "money", 
    "hp", "hpl", "george", "650", "lab", "labs", "telnet", "857", "data", "415", 
    "85", "technology", "1999", "parts", "pm", "direct", "cs", "meeting", "original", 
    "project", "re", "edu", "table", "conference", "semicol", "paren", "bracket", "bang", "dollar", 
    "pound", "cap_avg", "cap_long", "cap_total"]], spam_test_set['Class']

In [ ]:

# FUSED MODEL for #80%-20%

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#clf = RandomForestClassifier(n_estimators=100)
#clf = DecisionTreeClassifier(criterion = "entropy")
clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeighborsClassifier(n_neighbors=7)
#clf = AdaBoostClassifier(n_estimators = 200)
#LRI = LogisticRegression()
clf_lr = LogisticRegression()
clf_gnb = GaussianNB()
#clf = AdaBoostClassifier(n_estimators = 200,base_estimator=LRI)
eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')
#clf.fit(spam_training_data,spam_training_target)
eclf.fit(spam_training_data,spam_training_target)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


VotingClassifier(estimators=[('DT',
                              DecisionTreeClassifier(criterion='entropy')),
                             ('LR', LogisticRegression()),
                             ('GNB', GaussianNB())])

In [ ]:
#spam_test_target_predict=clf.predict(spam_test_data)
spam_test_target_predict =eclf.predict(spam_test_data)
confusion_matrix(spam_test_target,spam_test_target_predict)
#classification_report(spam_test_target,spam_test_target_predict)



array([[520,  43],
       [ 23, 335]])

In [ ]:
accuracy_score(spam_test_target,spam_test_target_predict)

0.9283387622149837

In [ ]:
#Adaboost classifier using decisiontree as base_learner for #80%-20%

from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
#clf = RandomForestClassifier(n_estimators=100)
clf = DecisionTreeClassifier(criterion = "entropy")
#clf_dt = DecisionTreeClassifier(criterion = "entropy")
#clf = KNeighborsClassifier(n_neighbors=7)
#clf = AdaBoostClassifier(n_estimators = 200)
#LRI = LogisticRegression()
#clf_lr = LogisticRegression()
#clf_gnb = GaussianNB()
clf = AdaBoostClassifier(n_estimators = 200,base_estimator=clf)
#eclf = VotingClassifier(estimators = [('DT', clf_dt),('LR',clf_lr),('GNB',clf_gnb)], voting ='hard')
clf.fit(spam_training_data,spam_training_target)
#eclf.fit(spam_training_data,spam_training_target)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy'),
                   n_estimators=200)

In [ ]:
#spam_test_target_predict=clf.predict(spam_test_data)
spam_test_target_predict =eclf.predict(spam_test_data)
confusion_matrix(spam_test_target,spam_test_target_predict)
#classification_report(spam_test_target,spam_test_target_predict)


array([[520,  43],
       [ 23, 335]])

In [ ]:

accuracy_score(spam_test_target,spam_test_target_predict)

0.9283387622149837